run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gocritic
    - gosec
#    - gofmt
    - goimports
    - errcheck
    - gosimple
    - unused
    - unconvert
    - goconst
    - gocyclo
    - revive

linters-settings:
  golint:
    min-confidence: 0.8

issues:
  exclude-use-default: false